// School and Professor Data Constants

export const schoolsList = [
  "School of Computer Science",
  "School of Law",
  "School of Liberal Studies",
  "School of Design",
  "School of Business",
  "School of Advanced Engineering",
  "School of Health Science",
];

export const schoolOfComputerScience = [
  "Prof. Vijaysekhar Chellaboina",
  "Dr. Vinod Patidar",
  "Dr. Neelu Jyothi Ahuja",
  "Dr. Hanumat Sastry G",
  "Prof. Karmeshu",
  "Dr. Madan Gopal",
  "Dr. Ajay Prasad",
  "Dr. Anil Kumar",
  "Dr. Hitesh Kumar Sharma",
  "Kaushik Ghosh",
  "Dr. Priya Ranjan",
  "Dr. Akashdeep Bhardwaj",
  "Mr. Pankaj Badoni",
  "Dr. Alok Aggarwal",
  "Dr. Sunil Gupta",
  "Dr. Deepika Koundal",
  "Dr. Vijendra Singh",
  "Dr. Sanjeev Kumar",
  "Dr. Suneet Kumar Gupta",
  "Dr. Surender Varma Gadhiraju",
  "Abadhan Sabyasachi",
  "Abhijit Kumar",
  "Abhirup Khanna",
  "Dr. Achala Shakya",
  "Dr. Ajay Kumar",
  "Akhilesh Mohan Srivastava",
  "Alind",
  "Alok Jhaldiyal",
  "Amar Jindal",
  "Amar Shukla",
  "Dr. Ambika Aggarwal",
  "Amit Gurung",
  "Dr. Anand Kumar",
  "Dr. Amit Verma",
  "Dr. Anish Kumar Vishwakarma",
  "Amrendra Tripathi",
  "Dr Ankit Kumar",
  "Anushree Sah",
  "Dr. Archana Kumari",
  "Dr. Arjun Arora",
  "Dr. Arundhati Tarafdar",
  "Dr. Aviral Sharma",
  "Avita Katal",
  "Mr. Avishek Majumder",
  "Bhavana Kaushik",
  "Dr. Bhupendra Singh",
  "Christalin Nelson S",
  "Deepak Kumar Sharma",
  "Dr. Deepa Joshi",
  "Dhirendra Kumar Sharma",
  "Dhiviya Rose J",
  "Gagan Deep Singh",
  "Dr. Gaurav Bhardwaj",
  "Gaytri",
  "Gopal Singh Rawat",
  "Goutam Datta",
  "Hemant Petwal",
  "Dr. Juhi Agrawal",
  "Dr. Jerry W. Sangma",
  "Kamal Raj Singh",
  "Dr. Kapil Gupta",
  "Dr. Keshav Sinha",
  "Kshitij Kumre",
  "Dr. Mitali Chugh",
  "Maithilee Laxmanrao Patawar",
  "Dr. Mohammad Ahsan",
  "Milton Kumar",
  "Dr. Muthukumar Ka",
  "Nadeem Yousuf Khanday",
  "Nayantara Kotoky",
  "Dr. Neeraj Chugh",
  "N Prasanthi Kumari",
  "Dr. Nitika Nigam",
  "Dr. Panduranga Ravi Teja",
  "Dr. Pankaj Kundan Dadure",
  "Dr. Pragya Katyayan",
  "Dr. Prabhat Ranjan Singh",
  "Piyush Rawat",
  "Dr. Prateek Raj Gautam",
  "Dr. Prateek Gupta",
  "Priyanka Singh",
  "Rahul Kumar Singh",
  "Rahul Kumar",
  "Dr. Ram Kumar",
  "Richa Choudhary",
  "Rohit Srivastava",
  "Dr. Rohit Tanwar",
  "Dr. Roohi Sille",
  "Sachi Choudhary",
  "Sahinur Rahman Laskar",
  "Sandeep Pratap Singh",
  "Prof. (Dr.) Sanjay Biswash",
  "Sanoj Kumar",
  "Saroj Snehal Shivagunde",
  "Shahid Sultan Hajam",
  "Shahina Anwarul",
  "Saurabh Shanu",
  "Dr. Shaurya Gupta",
  "Dr. Shiladitya Bhattacharjee",
  "Dr. Shreya Banerjee",
  "Shubhi Sharma",
  "Silky Goel",
  "Dr. Sonal Talreja",
  "Dr. Shresth Gupta",
  "Sugandha Sharma",
  "Dr. Supreet Singh",
  "Dr. Surbhi Saraswat",
  "Dr. Sushabhan Choudhury",
  "Suvojit Dhara",
  "Swati Rastogi",
  "Dr. Tanu Singh",
  "Dr. Tarandeep Kaur Bhatia",
  "Varun Sapra",
  "Ved Prakash Bhardwaj",
  "Dr. Vibhu Jately",
  "Vidyanand Mishra",
  "Yeshwant Singh",
  "Chhotelal Kumar",
  "Kotha Venugopalachary",
  "Manish Kumar Giri",
  "Virender Kadyan",
  "Dr. Mrittunjoy Guha Majumdar",
];

export const schoolOfAdvancedEngineering = [
  "Dr. Piyush Kuchhal",
  "Dr. Abhinav Sharma",
  "Dr. Devender Kumar Saini",
  "Dr. Harshit Mohan",
  "Dr. Sivasundar Manisankar",
  "Dr. Monika Yadav",
  "Dr. Rahul Singhal",
  "Dr. Ranjan Mishra",
  "Dr. Rupendra Kumar Pachauri",
  "Dr. Surajit Mondal",
  "Dr. Yogesh C. Gupta",
  "Dr. Nilanjana Banerjee",
  "Dr. Tirumala Rao Kotni",
  "Dr. Sunil Kumar Khare",
  "Dr. Srinivasa Reddy Devarapu",
  "Dr. Seim Timung",
  "Dr. Rohit Sharma",
  "Dr. Rahul Kumar",
  "Dr. Pushpa Sharma",
  "Dr. Prathibha Pillai",
  "Professor Pankaj Kumar Srivastava",
  "Mr. Niteen Ramchandra Yeole",
  "Dr. Ajay Mittal",
  "Dr. Amit Kumar Thakur",
  "Dr. Ashish Aggarwal",
  "Dr. Atul Kumar Patidar",
  "Dr. G. Gopalakrishnan",
  "Dr. Gaurav Pandey",
  "Dr. Girish Chandra Kothyari",
  "Dr. Himanshu Kesarwani",
  "Dr. Harinandan Kumar",
  "Jagadeeshwar Kodavaty",
  "Mr. Manash Protim Mudoi",
  "Dr. Mandira Agarwal",
  "Dr. Murali Pujari",
  "Dr. Nirlipta Priyadarshini Nayak",
  "Dr. Uday Bhan",
  "Dr. Vamsi Krishna Kudapa",
  "Dr. Ashish Karn",
  "Ajay Kumar",
  "Dr. Anil Kumar",
  "Dr. Ashish Mishra",
  "Dhiraj Kumar",
  "Donga Ramesh Kumar",
  "Dr. Gaurav Mittal",
  "Dr.Geetanjali Raghav",
  "Dr. Gurunadh Velladi",
  "Dr. Gurumayum Robert Kenedy",
  "Harshit Shukla",
  "Dr. Jitendra Yadav",
  "Kumar Gaurav",
  "Dr. Om Prakash",
  "Piyush Gaur",
  "Dr. Prashant Shukla",
  "Rajesh Maithani",
  "Ram Krishna Shah",
  "Dr. Ram Kunwer",
  "Ramesh Kumar",
  "Roushan Kumar",
  "Dr. Sachin Sharma",
  "Dr. Saurabh Kumar Bharti",
  "Siddharth Jain",
  "Dr. Subhankar Das",
  "Dr. Varun Pratap Singh",
  "Manish Kumar",
  "Dr. Abhishek Nandan",
  "Dr. Sunita Varjani",
  "Dr. Bikarama Prasad Yadav",
  "Dr. Balendu Shekher Giri",
  "Dharmendra Kumar Gupta",
  "Durga Prasad Panday",
  "Kanchan Deoli Bahukhandi",
  "Dr. Madhuben Sharma",
  "Prof. Rahul Silori",
  "Surendar Varadharajan",
  "Suvendu Manna",
  "Dr. Soumyaranjan Sahoo",
  "Dr. Ranjeet Kumar Brajpuriya",
  "Dr. Vipin Gaur",
  "Dr. Susmay Nandi",
  "Dr. Sravendra Rana",
  "Dr. Shilpi Agarwal",
  "Dr. Shikha Wadhwa",
  "Dr. Shefali Arora",
  "Dr. Shailey Singhal",
  "Dr. Sapna Jain",
  "Santosh Dubey",
  "Dr. Sanjeev Kumar",
  "Dr. Abhishek Kumar Mishra",
  "Dr. Aditya Sharma",
  "Dr. Akmal Husain",
  "Amit Awasthi",
  "Dr. Amit Kumar Chawla",
  "Dr. Amit Kumar Sharma",
  "Dr. Anil Kumar Sinha",
  "Dr. Ashishi Puri",
  "Dr. Ashish Mathur",
  "Dr. Anupam Bhandari",
  "Dr. Balendra Pratap Singh",
  "Dr. Bhuwan Chandra Joshi",
  "Dr. D.P. Singh",
  "Dr. Bhawna Yadav Lamba",
  "Dr. Debashis Ghosh",
  "Dr. Divya Ahluwalia",
  "Dr. Kailash Pandey",
  "Dr. Kanak Pal Singh Parmar",
  "Dr. KSR Murthy",
  "Dr. Monalisa Anand",
  "Dr. Manjeet Singh Goyat",
  "Dr. Manisha Malik",
  "Dr. Niloopher Salam",
  "Monika Manglik",
  "Navjot Hothi",
  "Prashant Shambhudayal Rawat",
  "Dr. Rajeev Gupta",
  "Dr. Raju Roychowdhury",
  "Dr. Rashmi Dubey",
  "Dr. Ratnesh K Pandey",
  "Ravi Kiran Maddali",
  "Reshu Gupta",
  "Dr. Ritesh Dubey",
  "Dr. Samar Layek",
  "Dr. Satya Krishna Nippani",
  "Dr. Sachin Pathak",
  "Dr. Sandeep Dixit",
  "Dr. Tanuj Kumar",
  "Dr. Vivek Panwar",
  "Dr. Shalendra Kumar",
];

export const schoolOfBusiness = [
  "Rahul Nainwal",
  "Dr. Niraj Shirish Mankad",
  "Prof (Dr) Sumeet Gupta",
  "Dr. Anita Sengar",
  "Dr. Atul Rawat",
  "Dr. Inder Singh",
  "Anil Kumar",
  "Arup Majumdar",
  "Dr. T. Bangar Raju",
  "Dr. P.C. Bahuguna",
  "Aanchal Sharma",
  "Dr. Ajit Yadav",
  "Dr. Amrita Chaskar",
  "Dr. Alok Negi",
  "Dr. Anirudh Singh",
  "Ankur Mittal",
  "Dr. Anmol Kumar Goyal",
  "Dr. Anup Kumar Yadava",
  "Ashish Pratap Singh",
  "ANURAG SHARMA",
  "Prof. Avishek Ghosal",
  "Bhumika Ray",
  "Dr. Bharat Ankur Dogra",
  "Deeksha Gupta",
  "Dr. Binod Kumar Singh",
  "Dr. Deepak Bangwal",
  "Dr. Deepak Ranjan",
  "Dr. Devkant Kala",
  "Gunjan Kumari",
  "Dr. Mohd Imran Khan",
  "Dr. Meenakshi Sharma",
  "Dr Kamlesh Kumar Maurya",
  "Ladenla Lama",
  "Dr. Mohammad Younus Bhatt",
  "Mohit Rishi",
  "Navdeep Bhatnagar",
  "Dr. Neeraj Kataria",
  "Neeraj Rathore",
  "Dr. Nida Rahman",
  "Dr. Pradeep Chauhan",
  "Preeti Aneja",
  "Puja Tiwari",
  "Dr. Rahul Bodhi",
  "Dr. Rakesh K. Meet",
  "Raj K Kovid",
  "Dr. Rajesh Mokale",
  "Rajeshwari Sharma",
  "Dr. Ranjeet Kumar Singh",
  "Sanjay Chaudhary",
  "Dr. Sanjay Malla",
  "Dr. Shalini Singh",
  "Dr. Shatrughan Yadav",
  "Dr. Shweta Agarwal",
  "Dr. Shailesh Pandita",
  "Dr. Soumen Rej",
  "Dr. Sonal Gupta",
  "Dr. Soumyajit Chakraborty",
  "Dr. Sushil Kumar Rai",
  "Dr. Sunil Barthwal",
  "Dr. Vijay Lahri",
  "Vikas Kumar",
  "Vaibhav Tripathi",
  "Manisha Solanki",
  "Santosh Anand",
  "Dr. Debjani Mukherjee",
  "Dr. Vijaya",
  "Dr. Tarunpreet Kaur Ahuja",
  "Rajesh Tripathi",
  "Dr. Pramod Kumar Painuly",
  "Dr. Badri Singh Bhandari",
];

export const schoolOfDesign = [
  "Prof. Bhaskar Bhatt",
  "Prof. Phani Tetali",
  "Rajan Iyer",
  "Jharna Joshi",
  "Soumitra Bhattacharya",
  "Ishan Khosla",
  "Abhishek Kumar",
  "Ajit Bhandari",
  "Avimesh Sharma",
  "Avni Joshi",
  "Ms. Baljinder Kaur",
  "Dr. Bappa Das",
  "DA Siddharth",
  "Dr. Debashis Majumder",
  "Gurpreet Singh",
  "Kishor Tikale",
  "Khushboo Bharti",
  "Lavendra Kumar Shukla",
  "Mekhla Harrison",
  "Mousim Mitra",
  "Milly Singh",
  "Nagesh Lakhan",
  "Dr. Naveen Kumar",
  "Nikhil Tikhe",
  "Dr. Nilakshi Yein",
  "Nilav Mazumdar",
  "Pariniti Singh",
  "Nitin Sharma",
  "Prabhakar Dabral",
  "Prasun Chakraborty",
  "Rakesh Ahirwar",
  "Rakesh Sah",
  "Dr. Samrat Dev",
  "Shirley Bhatnagar",
  "Siddharth Kumar",
  "Siddharth Prakash",
  "Siddharth Raje",
  "Siddhartha Mukherjee",
  "Sonal Singh",
  "Dr. Susmita Sharma Yadav",
  "Dr. Swati Sarkar",
  "Venkatesh Varala",
  "Vikas Thapa",
  "Vikram Mathur",
  "Vikrant Chandekar",
  "Vivek Kumar Pandey",
];

export const schoolOfHealthScience = [
  "Dr. Padma Venkat",
  "Jyoti Upadhyay",
  "Dr Kuldeep Kumar Roy",
  "Dr. Dhruv Kumar",
  "Dr. Smriti Arora",
  "Dr. Sunita Varjani",
  "Dr. Abhishek Chandra",
  "Dr. Amritansh Bhanot",
  "Dr. Anand Gaurav",
  "Dr. Anuradha Saini",
  "Deepanmol Singh",
  "Dr. Divya Tripathi",
  "Gufran Ajmal",
  "Dr. Gunjan Vasant Bonde",
  "Dr. Himanshi Jangir",
  "Dr. Iram Khan",
  "Dr. Kamesh Rajendra Babu",
  "Dr. Mitali Madhumita",
  "Nidhi Chauhan",
  "Dr. Nishu Goyal",
  "Dr. Piyush Kumar",
  "Dr. Prashant Shukla",
  "Dr. Rakesh Kumar Mishra",
  "Dr. Laxmi Kirola",
  "Dr. Subhajit Basu",
  "Dr. Ravi Rawat",
  "Dr Ranjna Sirohi",
  "Ravinder Kaushik",
  "Sandhya S",
  "Dr. Santosh Kumar Chaudhary",
  "Dr. Rajendra Awasthi",
  "Dr. Utsab Debnath",
  "Dr. Ramesh Kumar Saini",
  "Shikha Saxena",
  "Dr. Souradeep Roy",
  "Dr. Ramendra Pati Pandey",
  "Dr. Kapil Kumar",
  "Dr. Rohini Verma",
  "Ms. Richa Bahuguna",
  "Ms. Himani Nautiyal",
  "Dr. Shubham Dwivedi",
  "Dr. Snigdha Mishra",
  "Dr. Soumya Gupta",
  "Dr. Utkarsh Jain",
];

export const schoolOfLaw = [
  "Dr. Abhishek Sinha",
  "Dr. Shikha Dimri",
  "Dr. Balwinder Singh",
  "Govind Narayan Sinha",
  "Ashok Kumar Tyagi",
  "Dr. Anju Pandey",
  "Aditi Pateriya",
  "ABHIJIT B",
  "Aishwarya Vatsa",
  "Ajay Kumar",
  "Alind Gupta",
  "Dr. Kanchal Gupta",
  "Dr Gagandeep Kaur",
  "Anil Kumar Vishwakarma",
  "Dr. Aprajita Singh",
  "Ashutosh Tripathi",
  "Dr. Aarushi Batra",
  "Bharti Nair Khan",
  "Dr. Bhavana Rao",
  "Dr. Charu Srivastava",
  "Divya Dwivedi",
  "Ekta Yadav",
  "Ishan Maheshwari",
  "Dr. Latika Choudhary",
  "Dr. Manika Kamthan",
  "Mehreen Manzoor",
  "Monica Pradyot",
  "Dr. Nanda Pardhey",
  "Navin Pal Singh",
  "Neeti Goyal",
  "Nikita Begum Talukdar",
  "Dr Parth Sharma",
  "Pooja Gautam",
  "Dr. Pratiksha Bhardwaj",
  "Ms. Rachna Jha",
  "Rafique Khan",
  "Rohit Ranjan",
  "Ruby Yadav",
  "Sajal Sharma",
  "Ms. Sakshee Sharma",
  "Saksham Pradyot",
  "Sam Babu K C",
  "Samrat Datta",
  "Shatakshi Johri",
  "Shradha Baranwal",
  "Shreya Mahajan",
  "Shruti Dasgupta",
  "Dr. Sumit Kumar Pachauri",
  "Dr. Tauheed Alam",
  "Udit Raj Sharma",
  "Vaishali Singh",
  "Abhijit Anand",
  "Dr. Vinita Singh",
  "Arvind Singh Kushwaha",
  "Gaurav Mittal",
  "Aditya Rawat",
  "Anwesha Pathak",
  "Debarati Pal",
  "Dr. Himani Kaushik",
  "Dr. Hardik Daga",
  "Maria Devi Angerhofer",
  "Dr. Neha Singh",
  "Prachi Mishra",
  "Prafful Kumar Gupta",
  "Priyanka Choudhary",
  "Shibam Talukdar",
  "Shruti Chaturvedi",
  "Shriya Pandey",
  "Dr. Sujata Bali",
  "Dr. Tanveer Kaur",
  "Dr. Surya Saxena",
  "Udai Pratap Singh",
  "Dr. Yatish Pachouri",
  "Anushka Srivastava",
  "Anjali Bhatt",
  "Dr. Keshav Madhav",
];

export const schoolOfLiberalStudies = [
  "Prof. Atri Nautiyal",
  "Richa Chilana",
  "Himanshu Jha",
  "PLL Annapurna",
  "Dr. Aswani RS",
  "Dr. Melissa Reneaux",
  "Awadh Pratap Singh",
  "Sudha Tiwari",
  "Charusheel Tripathi",
  "Devaleena Kundu",
  "Dr. Amaresh Jha",
  "Gaurav Misra",
  "Jayadev Parida",
  "Jeeten Krishna Giri",
  "Dr. Roshni Sengupta",
  "Dr. Kshitiz Mishra",
  "Mahesh Sharma",
  "Mariyam Ilyas Siddiqui",
  "Dr. Pankaj Singh",
  "Ravindra Singh Rawat",
  "Dr. Ritam Dutta",
  "Sakshi Chanana",
  "Samir Kumer Das",
  "Satarupa Lahiri",
  "Shatavisha Mustafi",
  "Dr. Sudha Shashwati",
  "Dr. Uday Bhaskar Sharma",
  "Dr. Vinay Kumar Singh",
  "Dr. Sudipa Nag",
  "Sudeshna Chowdhury",
  "Neha Verma",
  "Dr . Seema Shukla",
  "Dr. Harshika Varma",
  "Dr. Kaustav Padmapati",
  "Dr. Abhishek Kumar Singh",
  "Minhaj Abdullah",
  "Pulkit Jain",
  "Srinath G.M.",
  "Rajiv Kumar",
  "Yamini Negi",
];
